"""
Static demo/seed data for LIFELINE Phase 1.

IMPORTANT: All coordinates below are DEMO/SEED DATA for prototype purposes.
Facility names are drawn from real Kisumu County institutions where noted,
but their coordinates are approximate placements for demonstration only and
have not been independently verified against surveyed GPS data. Treat them
as illustrative, not authoritative, until verified in a later phase.

All driver and patient names are fictional, generated by combining common
Kenyan given/surnames — they do not represent real people.
"""
from __future__ import annotations

# Kisumu city centre reference point, used to scatter generated facilities.
KISUMU_CENTER_LAT = -0.0917
KISUMU_CENTER_LON = 34.7680

# --------------------------------------------------------------------------
# Hand-curated major facilities (real Kisumu County institution names,
# approximate demo coordinates around Kisumu city and its sub-counties).
# --------------------------------------------------------------------------
MAJOR_HOSPITALS = [
    {
        "name": "Jaramogi Oginga Odinga Teaching & Referral Hospital",
        "facility_type": "NATIONAL_REFERRAL",
        "level": 6,
        "latitude": -0.1022,
        "longitude": 34.7617,
        "address": "Kakamega Road, Kisumu",
        "sub_county": "Kisumu Central",
        "bed_capacity": 500,
        "has_emergency_unit": True,
        "has_icu": True,
    },
    {
        "name": "Kisumu County Referral Hospital",
        "facility_type": "COUNTY_REFERRAL",
        "level": 5,
        "latitude": -0.0977,
        "longitude": 34.7580,
        "address": "Nairobi Road, Kisumu",
        "sub_county": "Kisumu Central",
        "bed_capacity": 350,
        "has_emergency_unit": True,
        "has_icu": True,
    },
    {
        "name": "Aga Khan Hospital, Kisumu",
        "facility_type": "PRIVATE_HOSPITAL",
        "level": 5,
        "latitude": -0.0895,
        "longitude": 34.7712,
        "address": "Otieno Oyoo Street, Kisumu",
        "sub_county": "Kisumu Central",
        "bed_capacity": 160,
        "has_emergency_unit": True,
        "has_icu": True,
    },
    {
        "name": "Avenue Hospital Kisumu",
        "facility_type": "PRIVATE_HOSPITAL",
        "level": 4,
        "latitude": -0.0951,
        "longitude": 34.7669,
        "address": "Achieng Oneko Road, Kisumu",
        "sub_county": "Kisumu Central",
        "bed_capacity": 90,
        "has_emergency_unit": True,
        "has_icu": True,
    },
    {
        "name": "Maseno Mission Hospital",
        "facility_type": "MISSION_HOSPITAL",
        "level": 4,
        "latitude": -0.0034,
        "longitude": 34.6003,
        "address": "Maseno, Kisumu County",
        "sub_county": "Kisumu West",
        "bed_capacity": 120,
        "has_emergency_unit": True,
        "has_icu": False,
    },
    {
        "name": "Ahero Sub-County Hospital",
        "facility_type": "SUB_COUNTY_HOSPITAL",
        "level": 4,
        "latitude": -0.1667,
        "longitude": 34.9167,
        "address": "Ahero Town",
        "sub_county": "Nyando",
        "bed_capacity": 100,
        "has_emergency_unit": True,
        "has_icu": False,
    },
    {
        "name": "Muhoroni Sub-County Hospital",
        "facility_type": "SUB_COUNTY_HOSPITAL",
        "level": 4,
        "latitude": -0.1500,
        "longitude": 35.1958,
        "address": "Muhoroni Town",
        "sub_county": "Muhoroni",
        "bed_capacity": 90,
        "has_emergency_unit": True,
        "has_icu": False,
    },
    {
        "name": "Nyakach Sub-County Hospital",
        "facility_type": "SUB_COUNTY_HOSPITAL",
        "level": 4,
        "latitude": -0.2833,
        "longitude": 34.9500,
        "address": "Pap Onditi, Nyakach",
        "sub_county": "Nyakach",
        "bed_capacity": 80,
        "has_emergency_unit": True,
        "has_icu": False,
    },
    {
        "name": "Kombewa Sub-County Hospital",
        "facility_type": "SUB_COUNTY_HOSPITAL",
        "level": 4,
        "latitude": -0.1000,
        "longitude": 34.5833,
        "address": "Kombewa Town",
        "sub_county": "Seme",
        "bed_capacity": 85,
        "has_emergency_unit": True,
        "has_icu": False,
    },
    {
        "name": "Chulaimbo Sub-County Hospital",
        "facility_type": "SUB_COUNTY_HOSPITAL",
        "level": 4,
        "latitude": -0.0561,
        "longitude": 34.6294,
        "address": "Chulaimbo",
        "sub_county": "Kisumu West",
        "bed_capacity": 75,
        "has_emergency_unit": True,
        "has_icu": False,
    },
    {
        "name": "Lumumba Health Centre",
        "facility_type": "HEALTH_CENTRE",
        "level": 3,
        "latitude": -0.1064,
        "longitude": 34.7539,
        "address": "Lumumba Estate, Kisumu",
        "sub_county": "Kisumu Central",
        "bed_capacity": 40,
        "has_emergency_unit": False,
        "has_icu": False,
    },
    {
        "name": "Nyalenda Health Centre",
        "facility_type": "HEALTH_CENTRE",
        "level": 3,
        "latitude": -0.1103,
        "longitude": 34.7669,
        "address": "Nyalenda Estate, Kisumu",
        "sub_county": "Kisumu Central",
        "bed_capacity": 35,
        "has_emergency_unit": False,
        "has_icu": False,
    },
]

# --------------------------------------------------------------------------
# Ward-name pool used to programmatically generate the remaining ~24
# smaller facilities (dispensaries / health centres) scattered around
# Kisumu County. Coordinates are jittered around KISUMU_CENTER during
# seeding — see database/seed.py.
# --------------------------------------------------------------------------
WARD_NAMES = [
    "Kondele", "Manyatta B", "Manyatta A", "Otonglo", "Kaloleni",
    "Nyamasaria", "Kolwa Central", "Kolwa East", "Kajulu", "Miwani",
    "Market Milimani", "Migosi", "Railways", "Shauri Moyo", "Kibos",
    "Bandani", "Dunga", "Kasule", "Kanyakwar", "Riat",
    "Korando", "Rabuor", "Nyahera", "Kisian", "Sigoma",
    "Wathorego", "Kabonyo", "Kobura", "Awasi", "East Kano",
]

FACILITY_NAME_SUFFIXES = ["Dispensary", "Health Centre"]

# --------------------------------------------------------------------------
# Fictional Kenyan name pools (drivers, patients, physicians). Purely demo
# data — not real people.
# --------------------------------------------------------------------------
KENYAN_FIRST_NAMES = [
    "Otieno", "Achieng", "Odhiambo", "Akinyi", "Omondi", "Atieno", "Owino",
    "Awuor", "Onyango", "Adhiambo", "Ochieng", "Anyango", "Okoth", "Auma",
    "Ouma", "Aoko", "Wafula", "Nafula", "Mwangi", "Wanjiru", "Kamau",
    "Njeri", "Kiplagat", "Chebet", "Barasa", "Nekesa", "Otieno Junior",
    "Achieng Grace", "Kevin", "Brian", "Faith", "Grace", "Mercy", "Peter",
    "John", "Mary", "Susan", "Daniel", "Caroline", "Collins",
]

KENYAN_SURNAMES = [
    "Odongo", "Obiero", "Okello", "Onyango", "Otieno", "Owuor", "Ogutu",
    "Opiyo", "Ojwang", "Oduor", "Odera", "Oyugi", "Wafula", "Kiptoo",
    "Njoroge", "Kariuki", "Mutua", "Wambui", "Cheruiyot", "Korir",
    "Adongo", "Akoth", "Ayieko", "Rono", "Simiyu",
]

HANDOVER_NOTE_TEMPLATES = [
    "Patient stable throughout transfer, vitals monitored every 15 minutes.",
    "Oxygen support administered en route; patient responsive on arrival.",
    "IV line maintained throughout transport, no complications noted.",
    "Patient remained conscious and alert; minor discomfort reported.",
    "Continuous monitoring performed; no adverse events during transfer.",
    "Patient condition unchanged from pickup to handover.",
]

INTERVENTION_TEMPLATES = [
    "Oxygen therapy via nasal cannula",
    "IV fluids administered (Normal Saline)",
    "Wound dressing and stabilization",
    "Continuous vital signs monitoring",
    "Splinting of affected limb",
    "Airway management",
]

MEDICATION_TEMPLATES = [
    "Paracetamol 1g IV",
    "Normal Saline 0.9% 500ml",
    "Diclofenac 75mg IM",
    "Oxygen 4L/min via nasal cannula",
    "Adrenaline 1mg IM (as per protocol)",
    "None administered en route",
]

REFERRAL_REASON_TEMPLATES = [
    "Requires specialist care not available at referring facility",
    "Needs ICU-level monitoring and management",
    "Requires surgical intervention",
    "Needs advanced diagnostic imaging",
    "Referred for specialist obstetric care",
    "Requires blood transfusion services",
    "Needs advanced trauma management",
    "Referred for paediatric specialist review",
]

CLINICAL_CONDITIONS = [
    "Road traffic accident with suspected fracture",
    "Acute abdominal pain, suspected appendicitis",
    "Obstetric emergency, prolonged labour",
    "Severe malaria with complications",
    "Suspected stroke",
    "Cardiac chest pain",
    "Severe pneumonia",
    "Acute asthma exacerbation",
    "Post-partum haemorrhage",
    "Suspected fracture, lower limb",
    "High-grade fever, unknown origin",
    "Diabetic emergency",
    "Snake bite envenomation",
    "Burns requiring specialist care",
    "Suspected meningitis",
]
